In [ ]:
#Import Numpy
import numpy as np  #np is alies so that can be used many times, called by .

In [ ]:
#Array defination

lst = [10,20,30]
print(type(lst))

<class 'list'>


In [ ]:
#numpy array defination

Arr = np.array(lst)
print(Arr)
print(type(Arr))

[10 20 30]
<class 'numpy.ndarray'>


In [ ]:
#Array defi

lst = [[10,20,30,4000]]

In [ ]:
array1 = np.array(lst)
print(array1)
print(type(array1))

[[  10   20   30 4000]]
<class 'numpy.ndarray'>


In [ ]:
#Checking the shape of the data

print(array1.shape) # 1row, 4 column- [[10,20,30,40]]

(1, 4)


In [ ]:
#2D array

darray = [[[10,20,30],[40,50,60]]]

array = np.array(darray)
print(array.shape)


(1, 2, 3)


In [ ]:
#3d array

tarray = [[10,20,30],[40,50,60]]

array = np.array(tarray)
print(array.shape)


(2, 3)


In [ ]:
#2D array

marray = [[[[10,20,30],[40,50,60],[70,80,90]]]]

array = np.array(marray)
print(array.shape)

(1, 1, 3, 3)


In [ ]:
#Checking dimensions of array

lst = [10,20,30]
array = np.array(lst)
print(array.ndim) #tell no. of array

1


In [ ]:
#Checking dimensions of array

lst = [[[[10,20,30]]]]
array = np.array(lst)
print(array.ndim) #tell no. of array

4


In [ ]:
zeros = np.zeros((3,4)) #3row, 4col, 3x4 matrix
print(zeros)
print(zeros.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
12


In [ ]:
zeros.T #transpose

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
eye = np.eye(4)
print(eye) #kernel filter ---> 3*3 matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
ones = np.ones((3,4)) #3row, 4col, 3x4 matrix
print(ones)
print(ones.size)
#outputs 1 float

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
12


In [ ]:
ones = np.array(ones)
'''
whenver we use empty, ary, by default the array contains float valu
'''

ones.sum()
print(ones.sum(axis = 0)) #operation column =s
print(ones.sum(axis = 1)) #perform opeation rowiswo
zeros.T #transpose



[3. 3. 3. 3.]
[4. 4. 4.]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones = np.array(ones)
'''
whenver we use empty, ary, by default the array contains float valu
'''

ones.sum()
print(ones.sum(axis = 0)) #operation column =s
print(ones.sum(axis = 1)) #perform opeation rowiswo
print(ones.size)
print(ones.ndim)

[3. 3. 3. 3.]
[4. 4. 4.]
12
2


In [ ]:
array1 = np.array([[10,20], [40,50]])
array2 = np.array([[10,20], [30,40]])

array3 = array1 + array2
print(array3)

[[20 40]
 [70 90]]


In [ ]:
#Aggregate functions

lst = [10,20,30]
array = np.array(lst)
print(array.sum())
print(array.min())
print(array.max())
print(array.mean())
print(array.prod())
print(array.var())
print(array.std())

60
10
30
20.0
6000
66.66666666666667
8.16496580927726


In [ ]:
a = np.array([[1,2,3,4,5,6],[10,20,30,40,50,60],[100,200,300,400,500,600],
              [1000,2000,3000,4000,5000,6000]]) #2d array, size 4*6

In [ ]:
print(a[:,:]) # : rows, : columns

[[   1    2    3    4    5    6]
 [  10   20   30   40   50   60]
 [ 100  200  300  400  500  600]
 [1000 2000 3000 4000 5000 6000]]


In [ ]:
print(a[1:2,:2])  #1:2, 2 rows tak matlab 2nd se kata, 1st row select[10,20,30,40,50,60] wala select; :2 2nd column tak kata sab, usse pehele ke only, 10,20 selected

[[10 20]]


In [ ]:
print(a[2:,3:5])

[[ 400  500]
 [4000 5000]]


In [ ]:
print(a[-1:-2,-1:-2])

[]


In [ ]:
print(a[0:1,2:4])

[[3 4]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2,0,0],[0,2,0],[0,0,2]]).T #tran
c = a*b

print(c)
print(c.ndim)
print(c.size)
print(c.shape)


[[ 2  0  0]
 [ 0 10  0]
 [ 0  0 18]]
2
9
(3, 3)


In [ ]:
a = np.array([[1,2],[4,5],[7,8]])
b = np.array([[2,0],[0,2],[0,0]])
c = a*b
print(c)
print(c.ndim)
print(c.size)
print(c.shape)



[[ 2  0]
 [ 0 10]
 [ 0  0]]
2
6
(3, 2)


In [ ]:
import pandas as pd

d = pd.DataFrame(c, columns = ['a', 'b'])

In [ ]:
d

a   b
0  2   0
1  0  10
2  0   0